create database if not exists SongEvents;
CREATE TABLE SONGS
(
	ARTIST_ID VARCHAR(100), 
	ARTIST_LATITUDE NUMERIC(20, 6),
	ARTIST_LOCATION VARCHAR(100),
	ARTIST_LONGTUDE NUMERIC(20, 6), 
	ARTIST_NAME VARCHAR(100), 
	SONG_DURATION_IN_SECONDS NUMERIC(20,6),
	ARTIST_NUM_OF_SONGS NUMERIC(5), 
	SONG_ID VARCHAR(100),
	SONG_NAME VARCHAR(100),
	SONG_REALASED_YEAR NUMERIC(5)
);
CREATE TABLE EVENTS
(
	ARTIST_NAME VARCHAR(200), 
	USER_AUTHONTICATION VARCHAR(200), 
	USER_FIRST_NAME VARCHAR(200),
	USER_GENDER VARCHAR(5),
	NO_ITEMS_IN_SESSION NUMERIC(10),
	USER_LAST_NAME VARCHAR(200), 
	SONG_LENGTH_IN_SECONDS NUMERIC(26, 6), 
	SONG_LEVEL VARCHAR(200), 
	USER_LOCATION VARCHAR(200), 
	SONG_METHOD VARCHAR(200), 	
	SONG_PLAYED VARCHAR(200), 
	USER_REGESTRATION_TIME_IN_SECONDS NUMERIC(26, 6), 
	SESSION_ID NUMERIC(5), 
	SONG_NAME VARCHAR(200), 
	SONG_STATUS NUMERIC(5), 
	TIME_IN_SECONDS_OF_PLAYING_SONG NUMERIC(26, 6), 
	USER_AGENT VARCHAR(400), 
	USER_ID NUMERIC(10)
);
